backend:
  name: git-gateway
  branch: master

local_backend: true  

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Upload newsletter PDF",
          name: "pdf",
          widget: "file",
          default: "/img/blog/default-pdf.pdf",
          required: false,
          multiple: false,
        }

  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "events-post",
        }
      - { label: "Title*", name: "title", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Start date*", name: "date", widget: "datetime" }
      - {
          label: "End date",
          name: "endDate",
          widget: "datetime",
          required: false,
        }
      - { label: "All day?", name: "allDay", widget: "boolean", default: false }
      - { label: "Short description*", name: "description", widget: "text" }
      - { label: "Body*", name: "body", widget: "markdown" }
      - { label: "Location*", name: "location", widget: "text" }
      - { label: "Cost* (0 for free)", name: "cost", widget: "number" }
      - { label: "URL", name: "url", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "aboutus"
    label: "About Us"
    files:
      - file: "src/pages/about-us/index.md"
        label: "About Us"
        name: "aboutus"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-text-links",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: Links,
              name: links,
              widget: list,
              fields:
                [
                  { label: Title, name: linkTitle, widget: string },
                  { label: Text, name: linkText, widget: text },
                  { label: Url, name: url, widget: string },
                ],
            }
      - file: "src/pages/about-us/african-vision-malawi-our-new-name/index.md"
        label: "African Vision Malawi - our new name"
        name: "ournewname"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about-us/how-we-started/index.md"
        label: "How we started"
        name: "howwestarted"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about-us/team/index.md"
        label: "Team"
        name: "teamPage"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-team",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Malawi Team",
              name: malawiTeam,
              widget: list,
              fields:
                [
                  { label: Photo, name: photo, widget: image },
                  { label: Name, name: name, widget: string },
                  { label: Role, name: role, widget: string },
                ],
            }
          - { label: "Malawi Title", name: "malawiTitle", widget: "string" }
          - { label: "Malawi Extra Text", name: "malawiText", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "UK Team",
              name: ukTeam,
              widget: list,
              fields:
                [
                  { label: Photo, name: photo, widget: image },
                  { label: Name, name: name, widget: string },
                  { label: Role, name: role, widget: string },
                ],
            }
          - { label: "UK Title", name: "ukTitle", widget: "string" }
          - { label: "UK Extra Text", name: "ukText", widget: "text" }
      - file: "src/pages/about-us/thank-yous/index.md"
        label: "Thank yous"
        name: "thankyous"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about-us/where-we-work/index.md"
        label: "Where we work"
        name: "wherewework"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "page-basic",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }      